[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 2000
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/contracts",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }